### ISSUE TITLE
[Question] uploadMce usage

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate-media-manager#9]
Hi,

I'm learning this package and I have a question about `uploadMce` method available within the `MediaManagerController`.
I can't understand if this method is it something useful, or it was used in an old version and stayed there by forgetfulness.

The only reference is within the file `mceextend.blade.php` which is called by the `boilerplate` package.
But actually, when I upload a file using the TinyMCE editor, the code use the `upload` method and the `uploadMce` is never used.

Could you please tell me what's the purpose of this?

Thanks in advance

**Comment by sebastienheyd** [comment]
Hi,

Good question, I think this is not used anymore. I have to check this point.

**Comment by cod3rshotout** [comment]
> Hi,
> 
> Good question, I think this is not used anymore. I have to check this point.

Thanks for the reply, I know what I'm about to ask you goes a little OT, but could I ask you for an opinion on an implementation I'm doing using your boilerplate?
Where can I contact you?

Thank you
